### ISSUE TITLE
Different Type of Items in Same Table - Best Practices Question

### ISSUE THREAD

**Issue by ebeltran1981** [alexdebrie/dynamodbguide.com#22]
Hi Alex,

I was at your talk in the AWS New York Summit few days ago... there you mentioned that most application will use only one table, and your example in the summit made a really good case for it... but now I found this website and I feel a bit confused! Could you clarify a bit?

> [Attributes, second paragraph](https://www.dynamodbguide.com/anatomy-of-an-item#attributes): [...]This isn't usually a best practice, but the flexible model of DynamoDB allows it if desired.

Thanks, and by the way, excellent presentation.

**Comment by alexdebrie** [comment]
@ebeltran1981 Thanks for pointing this out! That's incorrect, and I'll fix it. 

Glad you liked the presentation!

**Comment by alexdebrie** [comment]
Updated in [this PR](https://github.com/alexdebrie/dynamodbguide.com/pull/23) and live on the site. Thanks for raising!
