### ISSUE TITLE
Which part of a string

### ISSUE THREAD

**Issue by efleurine** [alexdebrie/dynamodbguide.com#8]
In [https://www.dynamodbguide.com/querying](https://www.dynamodbguide.com/querying) we use an expression on the OrderId key which is formatted as a datestamp and random generated number to retrieve a number of items in a specific time period.

```
aws dynamodb query \
    --table-name UserOrdersTable \
    --key-condition-expression "Username = :username AND OrderId BETWEEN :startdate AND :enddate" \
    --expression-attribute-values '{
        ":username": { "S": "daffyduck" },
        ":startdate": { "S": "20170101" },
        ":enddate": { "S": "20180101" }
    }' \
    $LOCAL
```
An OrderId would look like this `"20170609-25875"`, then how does Dynamodb knows that only the first part should be considerated in the comparison not also the random number part? I am sort in the dark here.

And does `BETWEEN` sort of convert the string to number to do the comparison?

**Comment by alexdebrie** [comment]
Hey @efleurine, great questions! I'll try to answer but let me know if it doesn't make sense.

The `OrderId` is a string type, not a number. When doing the `BETWEEN` operations, string values are ordered according to their UTF-8 bytes. Thus, you could imagine the ordering looking something like this:

```
20170101
20170101-00001
20170101-00002
20170101-00003
.....
20171231-99999
20180101
```

So when we specify "BETWEEN 20170101 AND 20180101", it will look for _any_ values between those two UTF-8 bytestrings.

Does that make sense?

**Comment by efleurine** [comment]
Yeah it make sense -

thanks @alexdebrie  for the quick reply and this great guide

**Comment by alexdebrie** [comment]
You're welcome! Going to close this :)
